# Change these first
owner: Altyrasolutionslda # GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository
sites:
  #APORMOR
  - name: Apormor
    url: $SECRET_SITE1
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconAPORMOR.ico
    assignees:
      - nevespt
  #CNCP
  - name: CNCP
    url: $SECRET_SITE2
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconCNCP.ico
  #FNAC (GC)
  - name: Gestão Campanhas
    url: $SECRET_SITE3
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconFNAC.ico
    assignees:
      - ivoprotasioAltyra
  #GV
  - name: Gestão Voluntariado
    url: $SECRET_SITE4
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconGV.ico
    assignees:
      - RProtasio
  #NaturalCarnes
  - name: Natur-Al-Carnes • Gestão
    url: $SECRET_SITENC1
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconNC.ico
    assignees:
      - nevespt
assignees: # Users to assign downtime issues
  - andrenevesgomes
status-website:
  baseUrl: /Uptime-Monitor
  theme: night
  #favicon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.png
  faviconSvg: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.svg
  logoUrl: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.png
  name: Altyra Solutions Status
  introTitle: "**Altyra Solutions Status** is an uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page which uses **real-time** data from our [GitHub repository](https://github.com/Altyrasolutionslda/Uptime-Monitor). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: https://altyrasolutionslda.github.io/Uptime-Monitor
    - title: GitHub
      href: https://github.com/Altyrasolutionslda
  metaTags:
    - name: "color-scheme"
      content: "#263c39"
    - name: "theme-color"
      content: "#263c39"
    - name: "msapplication-navbutton-color"
      content: "#263c39"
    - name: "apple-mobile-web-app-status-bar-style"
      content: "#263c39"
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
