# Change these first
owner: Altyrasolutionslda # GitHub organization or username, where this repository lives
repo: Uptime-Monitor # The name of this repository
sites:
  #APORMOR
  - name: Apormor
    url: $SECRET_SITE1
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconAPORMOR.ico
    assignees:
      - nevespt
  #CNCP
  - name: CNCP
    url: $SECRET_SITE2
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconCNCP.ico
  #FNAC (GC)
  - name: Gestão Campanhas
    url: $SECRET_SITE3
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconFNAC.ico
    assignees:
      - ivoprotasioAltyra
  #GV
  - name: Gestão Voluntariado
    url: $SECRET_SITE4
    icon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/iconGV.ico
    assignees:
      - RProtasio
assignees: # Users to assign downtime issues
  - andrenevesgomes
status-website:
  baseUrl: /Uptime-Monitor
  theme: night
  #favicon: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.png
  faviconSvg: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.svg
  customHeadHtml: "<!-- Primary Meta Tags -->
                  <title>Altyra Solutions Status is an uptime monitor and status page, powered entirely by GitHub.</title>
                  <meta name='title' content='Altyra Solutions Status is an uptime monitor and status page, powered                   entirely by GitHub.'>
                  <meta name='description' content='Altyra Solutions was born to meet the growing demand for tailor-made                  software development solutions. Our signature Let's make IT done reflects our commitment to developing                  solutions for the needs created by the challenging process of digital transformation of society and                 companies and organizations in particular.'>

                  <!-- Open Graph / Facebook -->
                  <meta property='og:type' content='website'>
                  <meta property='og:url' content='https://altyrasolutionslda.github.io/Uptime-Monitor/'>
                  <meta property='og:title' content='Altyra Solutions Status is an uptime monitor and status page, powered                  entirely by GitHub.'>
                  <meta property='og:description' content='Altyra Solutions was born to meet the growing demand for                   tailor-made software development solutions. Our signature Let's make IT done reflects our commitment to                   developing solutions for the needs created by the challenging process of digital transformation of                  society and companies and organizations in particular.'>
                  <meta property='og:image' content='https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/                 master/assets/data-analysis.jpg'>

                  <!-- Twitter -->
                  <meta property='twitter:card' content='summary_large_image'>
                  <meta property='twitter:url' content='https://altyrasolutionslda.github.io/Uptime-Monitor/'>
                  <meta property='twitter:title' content='Altyra Solutions Status is an uptime monitor and status page, powered entirely by GitHub.'>
                  <meta property='twitter:description' content='Altyra Solutions was born to meet the growing demand for tailor-made software development solutions. Our signature Let's make IT done reflects our commitment to                 developing solutions for the needs created by the challenging process of digital transformation of                  society and companies and organizations in particular.'>
                  <meta property='twitter:image' content='https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/data-analysis.jpg'>"
  logoUrl: https://raw.githubusercontent.com/Altyrasolutionslda/Uptime-Monitor/master/assets/logoAltyra.png
  name: Altyra Solutions Status
  introTitle: "**Altyra Solutions Status** is an uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page which uses **real-time** data from our [GitHub repository](https://github.com/Altyrasolutionslda/Uptime-Monitor). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: https://altyrasolutionslda.github.io/Uptime-Monitor
    - title: GitHub
      href: https://github.com/Altyrasolutionslda
  metaTags:
    - name: "color-scheme"
      content: "#263c39"
    - name: "theme-color"
      content: "#263c39"
    - name: "msapplication-navbutton-color"
      content: "#263c39"
    - name: "apple-mobile-web-app-status-bar-style"
      content: "#263c39"
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
